### PR TITLE
Media Login

### PR DESCRIPTION
**Pull request by PixelSculptor**

### CODE REVIEW

**Comment by glanttz** [comment]
Need to add two similar files (useFacebook and loginFacebook) because if i didnt do it and in signupform add router.push after calling function router doesnt work.

**Comment by glanttz** [comment]
So the only solution was adding two differents files to make out buttons work properly.

**Review by PixelSculptor — COMMENTED** [review]
@glanttz  Delete consol logs and rename folder json on for example apiData. Json is not readable for us

**Comment by glanttz** [comment]
i leave console.log when we log in and sign in in function like it is in signup/login with email and password.

**Comment by PixelSculptor** [comment]
give approve

**Review by glanttz — APPROVED** [review]

**Pull request merged**
