### PR TITLE
Referrals view

### PR DESCRIPTION
**Pull request by glanttz**
- add changes in referral view,
- add buttons for import and add referrals
- display list of import and added referrals
- add collections in userstore
- add fonts
- add listOfSpecializations in /utils
- make little changes in prescritinComponent

### CODE REVIEW

**Comment by PixelSculptor** [comment]
> * add changes in referral view,
> * add buttons for import and add referrals
> * display list of import and added referrals
> * add collections in userstore
> * add fonts
> * add listOfSpecializations in /utils
> * make little changes in prescritinComponent

@glanttz Glantz pls last view divide into smaller few PRs cause this is too big to check honestly ;) xd

**Comment by glanttz** [comment]
i write to you on mess about that

**Comment by glanttz** [comment]
because there here are commits from prescrition but prescriptions are merged in dev ;-;

**Comment by glanttz** [comment]
so i dont know whats going on. only what i do is refferals now. prescriptions you have checked.

**Pull request closed without merging**
